name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_SCANNER_OPTS: -X

  publish_image:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out 
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build . -t grcorreia/devops:latest
      - name: publish
        run: |
          docker login -u grcorreia -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push grcorreia/devops:latest