name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: yarn install
      - name: Construir aplicativo
        run: yarn build
      - name: Analisar com SonarQube
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Implantar no Docker
        uses: azure/docker-login@v1
        with:
          login-server: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Construir imagem do Docker
        run: docker build -t meu-app .
      - name: Implantar no Docker Hub
        run: docker push meu-app
