name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: SonarQube Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
        unzip sonar-scanner-cli-4.6.0.2311-linux.zip
        mv sonar-scanner-4.6.0.2311-linux /opt/sonar-scanner
        /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.projectKey=rodniski_devops \
          -Dsonar.sources=src \
          -Dsonar.language=js \
          -Dsonar.sourceEncoding=UTF-8
